### ISSUE TITLE
[Feature] Make tableheaders sticky

### ISSUE THREAD

**Issue by BennyAlex** [Niyko/Hydra-Dark-Theme-for-Adminer#12]
Hello,

It would be nice if the table headers would be stick on the top of the page when scrolling down.

I already tried https://github.com/stano/adminer-floatThead but it doesnt work with hydra.

**Comment by Niyko** [comment]
Hydra has this feature built-in, try without the plugin.

**Comment by BennyAlex** [comment]
@Niyko 
Hey, thanks for answer, but it does't work:

**Comment by Niyko** [comment]
Can I know the chrome version you are using?

**Comment by BennyAlex** [comment]
@Niyko 
Funny: At this view it does work.

I use latest chrome (88.0.4324.190) and also latest brave.

It's working in firefox!

**Comment by Niyko** [comment]
I will fix it. And I recommend you to delete the comment image which shows some confidential info about your working organization.

**Comment by BennyAlex** [comment]
Thank, theres nothing very confident but I will delete it :D

**Comment by daffamumtaz2361** [comment]
I'd open a pull request but honestly this is such a simple one-line fix

https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/blob/0078b0ed1dfef5bc56c38b4b77eda53ba2ca49b4/adminer.css#L682-L686

Just remove `overflow: hidden;` from there and the header would then stick.

**Comment by Niyko** [comment]
This is fixed in the latest release. @Zzombiee2361 Thanks for the suggestion, It really helped.
