### ISSUE TITLE
The 'references' line/arrow does not show in tables with foreign keys.

### ISSUE THREAD

**Issue by jhzrmx** [Niyko/Hydra-Dark-Theme-for-Adminer#19]
![Screenshot 2024-04-11 000021](https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/assets/122547859/d8d6b8b5-0a32-4589-a57e-4666ed05d7e7)
Under 'database schema', the 'references' line/arrow does not show under tables with foreign key.

**Comment by Niyko** [comment]
This issue is fixed in recent pull request. Thanks for your PR 😇
