### ISSUE TITLE
Horizontal Scroll Bar Missing

### ISSUE THREAD

**Issue by ThomasHineXYZ** [Niyko/Hydra-Dark-Theme-for-Adminer#3]
Horizontal scroll bars are missing on missing on smaller windows. (I use this on a section of a vertical monitor).

![image](https://user-images.githubusercontent.com/6890628/77383873-44098d80-6d41-11ea-8112-ff2bce106487.png)

**Comment by Niyko** [comment]
This issues has been fixed
