### ISSUE TITLE
CHAR column black

### ISSUE THREAD

**Issue by MaRmARk0** [Niyko/Hydra-Dark-Theme-for-Adminer#6]
Hi there. Just installed this theme and my MariaDB's `CHAR(5)` column appears like a black rectangle in Firefox v77.0.1

![Screenshot_1](https://user-images.githubusercontent.com/1789741/87404221-2bf29e00-c5be-11ea-9abf-fe96dcfc5d19.png)

**Comment by Niyko** [comment]
I have fixed it. Thanks for reporting :relaxed:
