### ISSUE TITLE
Language selection is bright white

### ISSUE THREAD

**Issue by ThomasHineXYZ** [Niyko/Hydra-Dark-Theme-for-Adminer#8]
The language selection in the bottom left corner is always bright white.

![Screenshot from 2020-07-24 03-29-48](https://user-images.githubusercontent.com/6890628/88382753-f5571900-cd5d-11ea-8a50-e3da9813ef26.png)

**Comment by Niyko** [comment]
I have fixed this and made the language selector to hover in right side. Thanks for reporting :relaxed:

**Comment by ThomasHineXYZ** [comment]
Oh nice. Looks pretty! Thank you.
