### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by crazynx** [Niyko/Hydra-Dark-Theme-for-Adminer#9]
How do I get the icons? 

For example, instead of showing a drag indicator icon, it just shows 'drag_indicator'.

![image](https://user-images.githubusercontent.com/64750127/89902909-5187bd00-dbe7-11ea-80ba-d65f1e5230af.png)

**Comment by Niyko** [comment]
Hi, Can I know which browser are you using, with the version if possible

**Comment by crazynx** [comment]
Hi, I am using Google Chrome on Linux, version  83.0.4103.116

**Comment by xu98** [comment]
Hi, i am using Google Chrome on Mac. How do I get the icons?
![image](https://user-images.githubusercontent.com/24386577/99362064-f48a5a00-28ed-11eb-8380-1dd10ccb49ed.png)

**Comment by Niyko** [comment]
This might be an issue with connecting to google icons CDN, Please check the CDN is not blocked
